language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pytest --upgrade
- pip install .
script:
- py.test tests
deploy:
  provider: pypi
  user: herrkaste
  password:
    secure: mjtqU413O5h4IYhB9iZVy5FqTGwqclvBrQXewQDps+uJJIuyhCVB7EYmWf+yBt22BF+iJtde/z9yJkuLm+wvsLRvg7YJRcNDbKlGJeOiNgcR6fiBUAKcTm3MTNXyKZhQ9YvTO2Hpk2Be+18867HIyC7K2IiUi+AYY/YwX7GCoQnXTRjQ4GGmAOnUW+bGFIQNjWz7j40UQMfofkW5br+j1OERD2OGK60VcNWb6hQPLB+KQRbQ7fxkf7ODkov3rixb5VaFQqhjxgfubGMSLSA9h3S21n8STGTxgJZnnyjmI1+4FbD+VtbZLTQivaqfkexqxt/EAdU5S6mITCSbajoXMn0qTW10vMCn6dSlhBrob/1JINi9Wu2c9tj6PDeQ0hO1MJKL00wNSFdyrkgef7qsgdByPunJjkjT9Ihfsi9GUSWz4OvmIYjfbejzwNqWuEgBa4iLDKTNYsOVJHIIgJX3Z93k/O11JlalZtwSOou9CNB8CC3u1anZbA2ZahUIJV7DfcaoDzXiC2V2Zm2gNOxUeaHFHJekSLlTErCQiFNr3uQL31J10EvX2AvuOPAwdSdrUDIkcTq52o0Jq47eRoDV/27bOiXxDLfAhbPTcLzSrneI5ITu9Q7YhP1fs7sYaWeNv2II4veQz+Ei0vWjeLVcvDue5JzVZPbdmIqh4zErIXs=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: kaste/pytest-mockito
